### ISSUE TITLE
Each E22 object should have sameAs links to museum permalinks when possible

### ISSUE THREAD

**Issue by rtroncy** [silknow/converter#70]
Currently, each `ecrm:E22_Man-Made_Object` is linked via `ecrm:P129_is_about` to a `crmdig:D1_Digital_Object`.

This Digital Object represent the metadata records:

- It follows a wrong URI pattern (see also #69) and has also a bizarre label, namely, the name of the JSON file.
- It has for ecrm:P2_has_type the string "Record" which should also be changed (see #35)

However, we have lost the original permalink (when available) of this object from the source museum. Not ALL museums do provide a permalink for their objects (e.g. CERES or GARIN does not) but some do. When there is such a permalink, there should be a `owl:sameAs` link between this permalink and the `ecrm:E22_Man-Made_Object`.

If this information is not present in the crawled JSON files, then a corresponding issue should be created in https://github.com/silknow/crawler/issues

**Comment by tschleider** [comment]
- The URI pattern is fixed (see #69)
- P2_has_type has been removed and `rdfs:label` has been changed accordingly (according to last zoom meeting)

I worked on the code to fetch the permalink, and this is easily possible, but I just need to finish to establish the `owl:sameAs` link. No crawler update necessary.

Example: 
https://ada-preprod.silknow.org/describe/?url=http%3A%2F%2Fdata.silknow.org%2Fobject%2F645ae680-04e7-3e15-bc9d-1e6f1bb68532&sid=393

**Comment by rtroncy** [comment]
Good, looking forward to see `owl:sameAs` links in each `E22_Man-Made_Object`

**Comment by tschleider** [comment]
Now implemented, too, and pushed to production, e.g.:

https://data.silknow.org/object/aca7cf7a-9ab0-3460-a98e-93a3bb734811

**Comment by rtroncy** [comment]
Hum, this is implemented as a string and not as a URI!

**Comment by tschleider** [comment]
True, I fixed it now, but FCT interprets it somehow. If you click on the raw data button it shows that it's now the correct URI: 

https://data.silknow.org/sparql?query=define%20sql%3Adescribe-mode%20%22CBD%22%20%20DESCRIBE%20%3Chttp%3A%2F%2Fdata.silknow.org%2Fobject%2Faca7cf7a-9ab0-3460-a98e-93a3bb734811%3E&output=application%2Fodata%2Bjson

**Comment by rtroncy** [comment]
There is still a problem with the value you're giving to the `owl:sameAs`. The goal is to link to ideally a permalink page from the source museum when it exists. But this should not be an API link for example. How did you construct this URI?

Example: <https://data.silknow.org/object/aca7cf7a-9ab0-3460-a98e-93a3bb734811> should NOT be `owl:sameAs` <https://www.vam.ac.uk/api/json/museumobject/O1113266> as this is the case at the moment BUT with <https://collections.vam.ac.uk/item/O1113266/>.

You will need of course to adapt / guess the construction rule for finding the permalink URI depending on the source URI (the pattern is easy for VAM) and this will sometimes NOT be possible. Read again the original description of the issue.

**Comment by tschleider** [comment]
Right now I grab the permalink from the harvested JSON, but VAM is a bad example because as far as I remember it's the only one (from which we crawl) that has an API link there.

But you're right that I need to fix this accordingly for the few cases where we need to guess or construct it.

**Comment by rtroncy** [comment]
OK, as a test case, I suggest you provide one example for each museum once this is fully implemented.

**Comment by tschleider** [comment]
VAM was indeed the only one for which it needed / could be constructed, now it's done, the example above is working now as you expected it.

For the rest, most of them are not worth a comment except:
- Garin: No permalink
- CER: No permalink
- Imatex: Permalink according to crawl, but the website does not let you acces it like this, e.g.: 
http://imatex.cdmt.cat/_cat/fitxa_fitxa.aspx?m=n&num_id=3023
- MTMAD: Website seems to be down: http://www.mtmad.fr/floracci/jsp/opac/opac_index.jsp?action=view_notice&recordId=musee:MUS_BIEN:796&only_main=true&lang=fre-FR
- Versailles: JSON does not contain any URI, I tried to see how they construct their permalinks on their website, but it doesn's seem trivial. I will ask @ehrhart about it.

**Comment by rtroncy** [comment]
- Indeed, there will be no permalink for GARIN and CER.
- MTMAD is connected to [this issue](https://github.com/silknow/crawler/issues/8). and I guess there is no hope for now. Note that the new? domain name is https://www.museedestissus.fr/ (and not http://www.mtmad.fr/) but this does not really help.
- For Imatex, it would be interesting to check if this is not a question of passing another parameter (like a token) to have it working.
- Looking for your final conclusion regarding Versailles

**Comment by ehrhart** [comment]
Regarding Versailles: they seem to have a really weird way of handling permalinks. Each search query generates a temporary session and the link to each object is unique to that session. Once it expires, the links won't work anymore. As far as I know there is no way to obtain true permalinks for this source.

**Comment by rtroncy** [comment]
OK, let's give up for Versailles then. Can you have a look at Imatex again to see if you can construct a URI that is dereferencable without an application code error?

**Comment by ehrhart** [comment]
For Imatex it requires a specific cookie (`ASP.NET_SessionId`) which can be obtained by first going to http://imatex.cdmt.es/. I don't think it's possible to construct an URI without the error. It's a shame that this is an issue and it looks more like a bug that should be fixed on their side.

**Comment by rtroncy** [comment]
OK, thanks for this final investigation. Now closing this issue.
@tschleider Keep this in mind for future/new museum dataset conversion to have this sameAs link implemented

**Comment by rtroncy** [comment]
I closed this issue too quickly. @tschleider Can you remove the `owl:sameAs` link in the case of imatex since there are not derefencable?

Example: https://data.silknow.org/object/470b0aab-ca56-37e3-a577-736931809d9b

Between, why does this object not have any label?

**Comment by tschleider** [comment]
Removed for Imatex (Is getting reconverted right now).

I checked the original JSON file and all text description fields are simply empty.

**Comment by tschleider** [comment]
@rtroncy : I was asked by Jorge in today's telecon to display the original URL per object, whenever possible (so excluding cases like Imatex) on ADASilk.
Therefore I open this issue here again (hopefully just for a short time).

**Comment by rtroncy** [comment]
Yes, I fully agree. What is the status? Do we have in most of the cases the museum permalink modeled as `owl:sameAs` in the KG?

@ehrhart Can you make sure that when this link is present, this is visualized in ADASilk?

**Comment by tschleider** [comment]
I simply forgot to update this but all museums that offer a working museum weblink have it now as owl:sameAs.

**Comment by ehrhart** [comment]
The `owl:sameAs` property is now being displayed under the title of the object.

**Comment by rtroncy** [comment]
Brilliant! Here is an example: https://ada.silknow.org/object/000c6e33-1bee-38db-9950-b6dba656f968
I'm closing this issue.
